# Generated by Django 3.1 on 2021-06-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
